### ISSUE TITLE
🐛 [BUG] 清理分享菜单 淘宝闪退

### ISSUE THREAD

**Issue by Sev73n** [Cemiuiler-Development-Team/Cemiuiler#60]
### 问题描述

点击清理分享菜单或者打开方式 选中淘宝
会引起淘宝直接闪退

### 模块日志

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Set
	at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:312)
	at w0.u0.k(Unknown Source:991)
	at w0.z.b(Unknown Source:58)
	at androidx.recyclerview.widget.LinearLayoutManager.K0(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.z0(Unknown Source:53)
	at androidx.recyclerview.widget.LinearLayoutManager.X(Unknown Source:856)
	at androidx.recyclerview.widget.RecyclerView.o(Unknown Source:78)
	at androidx.recyclerview.widget.RecyclerView.m(Unknown Source:124)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at moralnorm.springback.view.SpringBackLayout.onLayout(Unknown Source:40)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:874)
	at android.view.View.layout(View.java:23874)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4188)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3564)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2530)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9401)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

```Markdown
![图片注释](图片链接)
```

### 机型

小米

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.0

**Comment by mu7220** [comment]
不修
这是**淘宝**的问题，模块不会主动适配三方应用
